# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build DSU WAR
    runs-on: ubuntu-latest   # GitHub Runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven
      - name: List repo structure
        run: |
         echo "********* LIST REPO STRUCTURE **********"        
         ls -ltra & ll
      - name: Maven Build (WAR)
        run: mvn clean install -DskipTests

      - name: Upload WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: dsu-war
          path: wp-library-web/target/*.war
      
